### ISSUE TITLE
Error: refusing to allow an integration to create .github/main.workflow

### ISSUE THREAD

**Issue by luzpaz** [Azd325/gitkraken#105]
Manjaro Linux 18.0.3  
gitkraken 4.2.2  

When working on the homebrew/homebrew-core repo, when ever I push commits to my upstream fork I get an error message saying **refusing to allow an integration to create `.github/main.workflow`** but the file `.github/main.workflow` is not contained in my pull request.

Supposedly there is a workaround but I'm confused by it. 
https://github.com/cclauss/Upgrade-to-Python3/issues/1

Do I need to do something in regards to gitkraken ?

**Comment by Azd325** [comment]
Seems not related to gitkraken app
