### ISSUE TITLE
"Access token is invalid"

### ISSUE THREAD

**Issue by kmanwar89** [Azd325/gitkraken#114]
Hi there,

I just installed GitKraken today on my Arch installation, running i3-wm as my window manager. When I open GitKraken, I'm prompted to login. After clicking "Sign in with Github", I see the logo spinning, and an error stating "Access token is invalid".  

I'm assuming what is happening here is due to Firefox not opening in the background because I'm using a tiling window manager and not a traditional desktop environment.  All the options are shaded out, so I can't even generate a token manually like I do on my Windows machine.

Any advice on this would be appreciated. Thank you!

**Comment by thenexxuz** [comment]
Sounds like an issue to report to the GitKraken people. I would use their slack https://gitkraken.slack.com
