### ISSUE TITLE
LFS push permission error (non-executable shell script)

### ISSUE THREAD

**Issue by pafodie** [Azd325/gitkraken#135]
Working with a git-lfs repository, push fails with the error message
```
fatal: cannot exec /opt/gitkraken/resources/app.asar.unpacked/src/js/redux/domain/AskPass/askPass.sh: Permission denied
```

A simple `sudo chmod +x` on the file fixed this issue and Gitkraken works fine again.

Version: 6.5.4

**Comment by Azd325** [comment]
Sound like an issue directly for @Axosoft

**Comment by MarcinWieczorek** [comment]
Unless something has changed, they only have support email, no bug tracker. They never replied my emails regarding some issues in the past. Fixing a chmod in the package is nothing bad, but the guidelines require trying (and trying hard) upstream first.
@pafodie let us know when you attempt contacting them and lets give the issue some time.

**Comment by pafodie** [comment]
Sorry for late reply. Axosoft's response mentions 

https://github.com/Azd325/gitkraken/blob/12e4df21a13b143e645dfe76f869fcb9dac3925d/PKGBUILD#L41 

which unsets the executable flag from the file mentioned above.

**Comment by MarcinWieczorek** [comment]
I totally forgot about that line. Why is it even there? It was introduced 5 years ago, might not be needed anymore. So we either get rid of the find or chmod +x that one file. @pafodie do you want to patch?

**Comment by Azd325** [comment]
> I totally forgot about that line. Why is it even there? It was introduced 5 years ago, might not be needed anymore. So we either get rid of the find or chmod +x that one file. @pafodie do you want to patch?

Hmm, I'm also not more sure why I decided to use this line. 
Currently, I would prefer it if we set explicit the file mode on this file to make sure that we control what an executable and what not.

@MarcinWieczorek What you think?
