### ISSUE TITLE
Gitkraken doesn't show up anymore

### ISSUE THREAD

**Issue by SirMishaa** [Azd325/gitkraken#142]
Hello, 

For the past 2-3 weeks, Gitkraken doesn't seem to work anymore. (I have no problem when I install the package.)

When I open it via the console / menu, the application opens and closes directly, without any error message or anything.

Until a few weeks ago, I had no problems and did not make any major changes to my system.
```
OS : Manjaro 20.0.3 Lysia
Kernel : x86_64 Linux 5.6.16-1-MANJARO
DE : KDE 5.70.0 / Plasma 5.18.5
```

I tried to completely remove the package with pacman in order to reinstall it but without any success. I usually use yay to install it but I also tested with Octopi, no results either.

Can you tell me how to get logs or possible causes of this problem? Because I love Gitkraken and it's very annoying.

**Comment by Azd325** [comment]
I installed with `pamac build gitkraken` in a VirtualBox `manjaro kde 20.0.3` and Gitkraken was starting for me.

If you start Gitkraken in a terminal you should get enough information if something is wrong. Are you missing some dependencies?

**Comment by SirMishaa** [comment]
Can you tell me how to proceed? (To build gitkraken)

I will build the solution instead of installing it via the command ``pacman -S gitkraken``
For my part, I don't have any missing dependency errors.

**Comment by SirMishaa** [comment]
I've just performed this manipulation but the application still doesn't launch... Maybe it's a problem with my distribution in particular ? :(

![Screenshot_20200619_075257](https://user-images.githubusercontent.com/42717232/85101103-eaaae080-b201-11ea-8db5-0d190e1cb938.png)

**Comment by Azd325** [comment]
### Remove package

Check afterwards if `/opt/gitkraken` does not more exists.

`$ pacman -Rns gitkraken`

### Install package
https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages

```
$ Download PKGBUILD
$ makepkg -si
$ gitkraken
```

> Maybe it's a problem with my distribution in particular ? 

It works in a manjaro kde virtualbox. Very likely you broke your system somehow.

**Comment by SirMishaa** [comment]
![Screenshot_20200622_142954](https://user-images.githubusercontent.com/42717232/85287622-d92d3700-b494-11ea-81fe-faef15597c20.png)

**Comment by SirMishaa** [comment]
Fixed, I can install it. But I have a locale error, this is maybe why I can't start gitkraken ? 

![Screenshot_20200622_143557](https://user-images.githubusercontent.com/42717232/85288223-b0597180-b495-11ea-9c93-693b46978f50.png)

**Comment by Azd325** [comment]
> If you start Gitkraken in a terminal you should get enough information if something is wrong. Are you missing some dependencies?

Try to start from the console.

**Comment by SirMishaa** [comment]
It works when I start it with the console. 
When I start it with the shortcut, I get stuck and I'm forced to kill the process.
![Screenshot_20200622_144526](https://user-images.githubusercontent.com/42717232/85288989-04188a80-b497-11ea-91ca-90b8d583cda1.png)

**Comment by SirMishaa** [comment]
I don't know why when I use the console, it works, but thank you. 

If you have any ideas on how to fix the problem permanently, don't hesitate.

**Comment by Azd325** [comment]
@SirMishaa Which language do you use for your Manjaro?

**Comment by SirMishaa** [comment]
English, but I have some UTF-8 problems.

**Comment by SirMishaa** [comment]
Problem fixed.

It came from the fact that the `LC_ALL` variable was not exported and caused a problem with the UTF-8 encoding on my system.

See this: https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

Thank you.
