### ISSUE TITLE
Gitkraken GUI becomes partially unresponsive when switching away to CLI application

### ISSUE THREAD

**Issue by luzpaz** [Azd325/gitkraken#147]
I'm not always able to reproduce it but if I alt+tab away from gitkraken (and specifically to a CLI terminal eventually after some time (unsure)) upon returning to use gitkraken I won't be able to use some of it's functionality i.e. dropdown menu commands. I need to `killall gitkraken` and restart it in order for functionality to return.

```
OS: Manjaro 20.0.3 Lysia
 Kernel: x86_64 Linux 5.6.16-1-MANJARO
 Shell: bash 5.0.17
 Resolution: 4102x1152
 DE: KDE 5.70.0 / Plasma 5.18.5
 WM: KWin
 GTK Theme: Breath [GTK2/3]
 Icon Theme: breath2


gitkraken 7.0.1
```

**Comment by Azd325** [comment]
Open up if its still an issue.

**Comment by luzpaz** [comment]
I think this was an issue with X windows. So unrelated. Sorry, forgot to report that.
