### ISSUE TITLE
Gitkraken crash, when click Preferences and start again.

### ISSUE THREAD

**Issue by malyshkin-vitali** [Azd325/gitkraken#150]
Gitkraken crash, when click Preferences and start again. I try to install Gitkraken .deb file in Ubuntu(I hava Arch and Ubuntu on my PC) and it works!

Configuration

Operating system:
Arch Linux

Version of GitKraken:
7.3.0-1

Installation source - AUR

**Comment by GeoZac** [comment]
Browse through logs available at Help > Support logs to see any of the crashes got logged, or 

Try running gitkraken from console and see if it spits any error before quitting.

**Comment by malyshkin-vitali** [comment]
Hello, I see only error in terminal(screenshot in attach). When I click
Preferences terminal write : Cannot upload crash dump: cannot exec
/usr/bin/wget

Unexpected crash report id length
Failed to get crash dump id.
Report Id:




сб, 5 сент. 2020 г. в 13:05, George Zacharia <notifications@github.com>:

**Comment by Azd325** [comment]
> Preferences terminal write : Cannot upload crash dump: cannot exec
/usr/bin/wget

It seems that `wget` ist missing.

**Comment by malyshkin-vitali** [comment]
Okay, I will try to install it and check.

**Comment by malyshkin-vitali** [comment]
> > Preferences terminal write : Cannot upload crash dump: cannot exec
> > /usr/bin/wget
> 
> It seems that `wget` ist missing.

I have installed the wget, the error was't solved but the error have changed.

<pre>(node:6853) Electron: Loading non-context-aware native module in renderer: &apos;/opt/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node&apos;. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:6853) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:6853) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
state:  update-not-available
--2020-09-07 18:18:27--  https://crash.gitkraken.com/submit
Loaded CA certificate &apos;/etc/ssl/certs/ca-certificates.crt&apos;
Resolving crash.gitkraken.com (crash.gitkraken.com)... 174.46.225.159
Connecting to crash.gitkraken.com (crash.gitkraken.com)|174.46.225.159|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40 [text/html]
Saving to: ‘/dev/fd/4’

/dev/fd/4             0%[                    ]       0  --.-KB/s               
Failed to get crash dump id./dev/fd/4           100%[===================&gt;]      40  --.-KB/s    in 0s      
Report Id: 
bp-7445c297-bb0a
</pre>

I need your help.

**Comment by malyshkin-vitali** [comment]
On Ubuntu 20.04 LTS(Installed from .deb) preferences work. I have this in terminal on start and nothing when I click prefences:

<pre>vitalya@Vitalya-PC:~$ gitkraken 
state:  update-not-available
state:  checking-for-update
(node:3262) Electron: Loading non-context-aware native module in renderer: '/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-ubuntu-18.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:3262) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:3262) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
state:  update-not-available
(node:3262) Electron: Loading non-context-aware native module in renderer: '/usr/share/gitkraken/resources/app.asar.unpacked/node_modules/font-scanner/build/Release/fontmanager.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

</pre>

**Comment by malyshkin-vitali** [comment]
I don't know why, but with <pre>sudo gitkraken --no-sandbox</pre> gitkraken works correctly.

**Comment by malyshkin-vitali** [comment]
What do you think about it?

**Comment by Azd325** [comment]
> > > Preferences terminal write : Cannot upload crash dump: cannot exec
> > > /usr/bin/wget
> > 
> > 
> > It seems that `wget` ist missing.
> 
> I have installed the wget, the error was't solved but the error have changed.
> 
> (node:6853) Electron: Loading non-context-aware native module in renderer: '/opt/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
> (node:6853) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (node:6853) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
> state:  update-not-available
> --2020-09-07 18:18:27--  https://crash.gitkraken.com/submit
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving crash.gitkraken.com (crash.gitkraken.com)... 174.46.225.159
> Connecting to crash.gitkraken.com (crash.gitkraken.com)|174.46.225.159|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 40 [text/html]
> Saving to: ‘/dev/fd/4’
> 
> /dev/fd/4             0%[                    ]       0  --.-KB/s               
> Failed to get crash dump id./dev/fd/4           100%[===================>]      40  --.-KB/s    in 0s      
> Report Id: 
> bp-7445c297-bb0a
> I need your help.

It looks like a general problem. Gitkraken should got a report of you from this test.

**Comment by malyshkin-vitali** [comment]
What about you? Do you have this problem in Arch?

**Comment by AurevoirXavier** [comment]
Same error.

```
λ gitkraken -l log
 
state:  update-not-available
 
state:  checking-for-update
 
(node:165173) Electron: Loading non-context-aware native module in renderer: '/opt/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node'.
 
This is deprecated, see https://github.com/electron/electron/issues/18397.
 
(node:165173) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead
 
.
 
(node:165173) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
 
state:  update-not-available
 
--2020-09-11 02:48:27--  https://crash.gitkraken.com/submit
 
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
 
Connecting to 0.0.0.0:7890... connected.
 
Proxy request sent, awaiting response... state:  checking-for-update
 
(node:165300) Electron: Loading non-context-aware native module in renderer: '/opt/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node'.
 
This is deprecated, see https://github.com/electron/electron/issues/18397.
 
(node:165300) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead
 
.
 
(node:165300) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
 
200 OK
 
Length: 40 [text/html]
 
Saving to: ‘/dev/fd/4’
 
/dev/fd/4                                         0%[                                                                                                      ]       0  --.-KB/s                
 
Failed to get crash dump id./dev/fd/4                                       100%[=====================================================================================================>]      
 
40  --.-KB/s    in 0s       
 
Report Id:  
 
bp-643a4bd9-5122
 
state:  update-not-available
```

```
λ gitkraken -d SILLY

state:  update-not-available

state:  checking-for-update

(node:3275) Electron: Loading non-context-aware native module in renderer: '/opt/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node'. Th

is is deprecated, see https://github.com/electron/electron/issues/18397.

(node:3275) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

(node:3275) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.

state:  update-available

--2020-09-12 20:08:08--  https://crash.gitkraken.com/submit

Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'

Connecting to 0.0.0.0:7890... connected.

Object has been destroyed

TypeError: Object has been destroyed

   at BrowserWindow.<anonymous> (<embedded>:10:222336)

   at e (<embedded>:10:34171)

   at c (<embedded>:10:34425)

   at Timeout.f [as _onTimeout] (<embedded>:10:34321)

   at listOnTimeout (internal/timers.js:531:17)

   at processTimers (internal/timers.js:475:7)
```

**Comment by Azd325** [comment]
Looks like a general problem.

cc @Axosoft

**Comment by AurevoirXavier** [comment]
Few days, it works good. 

After I re install the Arch Linux. It crash. Maybe I miss some dependencies? But the log didn't give any useful informations

**Comment by malyshkin-vitali** [comment]
I have written to Gitkraken developers. Unfortunately, they said that ArchLinux is not supported by them and this problems are my problems. They supported only Ubuntu 16.04 LTS+, RHEL 7+, CentOS 7+, and Fedora 30+. I am very disappointed.

**Comment by AurevoirXavier** [comment]
> I have written to Gitkraken developers. Unfortunately, they said that ArchLinux is not supported by them and this problems are my problems. They supported only Ubuntu 16.04 LTS+, RHEL 7+, CentOS 7+, and Fedora 30+. I am very disappointed.

Have you try downgrade the version? Few days ago it works perfectly.

BTW, without the preference UI is OK. Do you know how to config in the file?

**Comment by malyshkin-vitali** [comment]
No I don't know how to config. I have tried 7.3.0, 7.3.1, and 7.3.2 versions. All versions crashed.

**Comment by Azd325** [comment]
I had time to test for myself and it worked fine out of the box.

Tested with 7.3.2

**Comment by Azd325** [comment]
Reopen if you have new informations about it.

**Comment by AurevoirXavier** [comment]
Don't know why still crash.

But in other fresh new archlinux machine, It works good.

**Comment by malyshkin-vitali** [comment]
> Don't know why still crash.
> 
> But in another fresh new installed archlinux machine, it works good.
> 
> Is there any cache that I should clean?

I also tried install ArchLinux on my laptop and gitkraken works. It" s strange. But on my PC it doesn't work. Pc and laptop archlinux are up-to-date

**Comment by AurevoirXavier** [comment]
> > Don't know why still crash.
> > But in another fresh new installed archlinux machine, it works good.
> > Is there any cache that I should clean?
> 
> I also tried install ArchLinux on my laptop and gitkraken works. It" s strange. But on my PC it doesn't work. Pc and laptop archlinux are up-to-date

What's your cpu?

**Comment by malyshkin-vitali** [comment]
> > > Don't know why still crash.
> > > But in another fresh new installed archlinux machine, it works good.
> > > Is there any cache that I should clean?
> > 
> > 
> > I also tried install ArchLinux on my laptop and gitkraken works. It" s strange. But on my PC it doesn't work. Pc and laptop archlinux are up-to-date
> 
> What's your cpu?

Laptop: Intel core i5 8250U.
PC: AMD FX 8320.
But Gitkraken works fine with my PC on Ubuntu 20.04.

**Comment by AurevoirXavier** [comment]
> > > > Don't know why still crash.
> > > > But in another fresh new installed archlinux machine, it works good.
> > > > Is there any cache that I should clean?
> > > 
> > > 
> > > I also tried install ArchLinux on my laptop and gitkraken works. It" s strange. But on my PC it doesn't work. Pc and laptop archlinux are up-to-date
> > 
> > 
> > What's your cpu?
> 
> Laptop: Intel core i5 8250U.
> PC: AMD FX 8320.
> But Gitkraken works fine with my PC on Ubuntu 20.04.

All my intel PC works good. Only crash on amd.

**Comment by lemmingz** [comment]
It crashes even well on my Intel CPU. 

May it depend on protected ssh- or gpg-keys?

**Comment by malyshkin-vitali** [comment]
> It crashes even well on my Intel CPU. May it depend on protected ssh- or gpg-keys?
> […](#)
> Am 10.10.2020 um 14:51 schrieb Xavier Lau ***@***.***>: ﻿ Don't know why still crash. But in another fresh new installed archlinux machine, it works good. Is there any cache that I should clean? I also tried install ArchLinux on my laptop and gitkraken works. It" s strange. But on my PC it doesn't work. Pc and laptop archlinux are up-to-date What's your cpu? Laptop: Intel core i5 8250U. PC: AMD FX 8320. But Gitkraken works fine with my PC on Ubuntu 20.04. Same. All my intel PC works good. Only crash on amd. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I think no cause I ve tested the same github account in arch and ubuntu. Ubuntu is ok, but arch is not.

**Comment by AurevoirXavier** [comment]
Please reopen this

**Comment by lemmingz** [comment]
It still crashes on 7.4.0.

**Comment by AurevoirXavier** [comment]
Solved.

```
pacman -S gnome
```

But too many packages. Could you find out which one is needed? @Azd325

**Comment by malyshkin-vitali** [comment]
> Solved.
> 
> ```
> pacman -S gnome
> ```
> 
> But too many packages. Could you find out which one is needed? @Azd325

Just reinstall gnome group? Rly? But I can't understand how it can help, cause versions od packages won't change.

**Comment by AurevoirXavier** [comment]
Not just reinstall.

I'm on kde plasma. I missing so many dependencies.

**Comment by malyshkin-vitali** [comment]
> Not just reinstall.
> 
> I'm on kde plasma. I miss so many gnome dependencies.

Lol, I on gnome 3 and gitkraken crush at preferences) Magic)

**Comment by AurevoirXavier** [comment]
> > Not just reinstall.
> > I'm on kde plasma. I miss so many gnome dependencies.
> 
> Lol, I am on gnome 3 and gitkraken crush at preferences) Magic)

Maybe you miss something in KDE? LOL!

**Comment by lemmingz** [comment]
I have two machines, both ArchLabs Linux, but slightly different setup. On one it crashes, on the other one everything is fine. But I dont know hoe to further investigate.

**Comment by Azd325** [comment]
Compare the packages of the two machines. Current assumption of this thread, it is missing a package.

**Comment by lemmingz** [comment]
On my machine on which GitKraken was crashing before, using 7.4.1 is fine now with opening preferences!

**Comment by Azd325** [comment]
> On my machine on which GitKraken was crashing before, using 7.4.1 is fine now with opening preferences!

Sounds great. Did you have any major changes on your system?

**Comment by lemmingz** [comment]
No, I did nothing beyond regular pac-man updates.

**Comment by malyshkin-vitali** [comment]
Works fine. Upgrade all system with pacman and upgrade Gitkraken.

**Comment by NKnusperer** [comment]
Same issue here as described in #164:
```
(gitkraken:524276): Gtk-WARNING **: 08:24:34.758: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
(electron) 'allowRendererProcessReuse' is deprecated and will be removed.
state:  unavailable
state:  checking
state:  unavailable
WebContents 2 render process unexpectedly missing: crashed
[PERFORMANCE] tried to end event with no start time: opening renderer window
```

KDE Plasma: 5.21.4
KDE Framework: 5.821.0
Qt: 5.15.2

No error is generated :(

**Comment by NKnusperer** [comment]
I just installed GitKraken via KDE Discover an now it is working.
Still no idea what the problem with the AUR package is.

**Comment by thirdbrainsa** [comment]
I am stick on 7.4.1 all others version after are crashing on my Ubuntu 16

**Comment by BohdanK911** [comment]
**GitKraken 7.7.2, still same issue**
OS: Manjaro Linux [x86_64]
Host: 80Y7 Lenovo YOGA 920-13IKB
Kernel: 5.13.13-1-MANJARO
Packages: 1466 (pacman)[stable]
Shell: zsh 5.8
DE: GNOME 40.4
WM: Mutter (X11)
Terminal: gnome-terminal-server
CPU: Intel Core i7-8550U (8) @ 4GHz
GPU: Intel UHD Graphics 620

**Comment by tufei** [comment]
Fedora 33 after updating to the latest GitKraken, noticed the same issue.

**Comment by grummbeer** [comment]
currently 8.0.0, but this has been happening since 7.4.x or so

When opening preferences

```
App Window: WebContents 4 render process unexpectedly missing: crashed
MessagePort is terminating
MessagePort is terminating
MessagePort is terminating
MessagePort is terminating
[PERFORMANCE] tried to end event with no start time: opening renderer window
Error occurred in handler for 'LOAD_ORGANIZATION_SUMMARIES': TypeError: Object has been destroyed
    at <embedded>:1:112351
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async electron/js2c/browser_init.js:189:542
state:  checking
state:  unavailable
```

When clicking "Open in Terminal Tab"
```
pp Window: WebContents 3 render process unexpectedly missing: crashed
MessagePort is terminating
MessagePort is terminating
[PERFORMANCE] tried to end event with no start time: opening renderer window
Object has been destroyed
TypeError: Object has been destroyed
    at BrowserWindow.<anonymous> (<embedded>:10:734344)
    at e (<embedded>:10:34174)
    at c (<embedded>:10:34428)
    at Timeout.f [as _onTimeout] (<embedded>:10:34324)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
state:  checking
state:  unavailable
```

Immediately after the restart 
```
(node:21739) UnhandledPromiseRejectionWarning: Error: forbidden
    at buildError (<embedded>:10:747606)
    at IncomingMessage.<anonymous> (<embedded>:10:749304)
    at IncomingMessage.emit (events.js:310:20)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:21739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21739) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Operating System: openSUSE Tumbleweed 20210920
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.14.5-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770K CPU @ 3.50GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

**Comment by vicentedpsantos** [comment]
I was having the same issue when I installed gitkraken using the AUR repo. Uninstall the AUR package `pacman -R gitkraken` and then reinstall the package from snapstore, that seems to be working fine (https://snapcraft.io/gitkraken)

**Comment by grummbeer** [comment]
version 8.2

Too bad, on my system the font (inconsolata) was not installed and after adding it, reboot. Still crash when trying to open the preferences.

The last time iam using the tar.gz, since 8.1 i install the .rpm with rpm -i. Since then i cannot see the ouput on the console anymore. The command `gitkraken` open gitkraken, but does not output somthing to the console. How i can get the console logging back?

**Comment by grummbeer** [comment]
Yesterday i realized that this here is the arch userland … so i did somthing really crazy, i contact the axosoft support (paying user).

The answer was:

>  There is a known issue that this can happen from some specific custom fonts. Specifically, we are aware that RedHat and JetBrains Mono fonts can cause this. If you have these or another custom font installed, you should be able to remove them from the fonts folder in your OS to address this.  

And yes, i am actually using phpstorm with "Jetbtrains Mono" as the font for the editor-view … Iam asked back if there is a plan to fix that.

**Comment by tufei** [comment]
The catch for me is, I just could not find a text configuration file for GitKraken even if I wanted to check what editor UI font I used. I vaguely remembered I did choose another custom font, which was not the default.

So even if I wanted to revert back, without opening the "Preference" window I cannot do it.

Does anyone happen to know the configuration file in which to change editor UI font selection?

**Comment by michsko544** [comment]
Same problem
OS: Ubuntu 20.04.4 LTS x86_64
GitKraken 8.5.0

My GitLab token has expired and token refresh returned error 1007 when I tried to go to preferences it crushed my app.

**Comment by grummbeer** [comment]
@michsko544 

From my side I can confirm that the problems with tumbleweed and GitKraken 8.5 are gone. since 8.3 or so.

I thought that Gitkraken fixed it, but now I'm not sure. You are on LTS, maybe some system updates did the job at my side

**Comment by Neko-Box-Coder** [comment]
I have had this for quite a while, I am using KDE Manjaro.
I don't have ttf-inconsolata installed after installing it, the preference is no longer crashing for god knows whatever reason lol

**Comment by michsko544** [comment]
I still have a problem :(
OS: Ubuntu 22.04.1 LTS x86_64
GitKraken 8.8.0
ttf-inconsolata installed

**Comment by grummbeer** [comment]
> mscore-font

Are you on Windows? Than the latest bugfix ~~is~~ could for you.

https://help.gitkraken.com/gitkraken-client/current/#version-8-9-1

Version 8.9.1
Wednesday, September 14th, 2022
Bug Fixes 🐛

- Fixed an crash on some Windows machines when opening the Preferences menu.

> Maybe you have to contact gitkraken support if you need the font to be installed which causes the crashes...

Although I can open the settings again since 8.3 or so but gitkraken sill freezes when I try to select another font for the Editor under Settings | Editor. I Asked the support already a while ago and got no answer about that. Software that relies on a specific font (there are a lot of candidates around already) looks still strange to me.

**Comment by Llemaban** [comment]
> Are you on Windows?

No, both times on Linux (Mint 20 and Fedora 36). On Windows I never had such an issue.

**Comment by ndkhaivn** [comment]
> I had the same problem today, the Preferences just wouldn't open. I was able to fix it, for that I removed the font [ttf-inconsolata](https://archlinux.org/packages/community/any/ttf-inconsolata/) and that's it.
> 
> ```shell
> sudo pacman -R ttf-inconsolata
> ```

Worked for me

**Comment by reka18** [comment]
Use the flatpak or Snap version of Gitkraken. These do not seem to have the bug.
