### ISSUE TITLE
Not connecting to Github/Gitlab/Bitbucket

### ISSUE THREAD

**Issue by GuilhermeHaetinger** [Azd325/gitkraken#152]
This might not be a problem with the AUR package itself but mostly with the compatibility with Arch. I tried all the possible installation methods and it keeps refusing to connect with Github. I simply click on the connect button at any point (login or at integrations) and it immediately goes back to "not connected". The logs/app.txt shows this lines 

```
[2020-10-16T17:12:40.957Z] Request OAuth token from GitHub: started.
[2020-10-16T17:12:41.021Z] Request OAuth token from GitHub: [object Event]
[2020-10-16T17:12:41.023Z] Request OAuth token from GitHub: finished with errors. gk-log://duration?t=66
```

I don't really know how to debug this properly. I used strace but it didn't give me an useful output (for all I know). When I run the program with sudo, it hangs on "connecting". In no point does it open the browser for these integrations. It opens it for Trello and Jira, though.

I tried reaching out in the Slack server but no one got back to me.

**Comment by Azd325** [comment]
On my side it works. Does your browser open up, if you click on connect?

Browse through logs available at Help > Support logs to see any of the crashes got logged, or (You may need to install wget.)

Try running gitkraken from console and see if it spits any error before quitting.

**Comment by GuilhermeHaetinger** [comment]
I am pretty sure this is an error on my end. But it can probably happen to someone else, so I would like to get to the bottom of this.

The thing is, it doesn't really quit/crash. It just doesn't open the browser and goes back to not being connected. In the other hand, Trello and Jira open the browser and connect.
The Activity logs show the same thing as my comment above. The error logs are empty.

I have wget installed. I ran it from the console but disregarded the warnings because they seem to be standard deprecated warnings:
```
state:  update-not-available
state:  checking-for-update
(node:5672) Electron: Loading non-context-aware native module in renderer: '/opt/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:5672) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
state:  update-not-available
(node:5672) Electron: Loading non-context-aware native module in renderer: '/opt/gitkraken/resources/app.asar.unpacked/node_modules/font-scanner/build/Release/fontmanager.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```
The last line happens when I go into the integrations tab.

**Comment by Azd325** [comment]
Are you running the latest gitkraken?

Maybe reset the gitkraken and try to login with github on the profile creation.

**Comment by GuilhermeHaetinger** [comment]
Yeah, I'm running the latest AUR gitkraken and this error happens from the start of a clean install. If I try connecting on the profile creation page, It goes directly to this screen:
![image](https://user-images.githubusercontent.com/23220288/96348298-06be7180-107e-11eb-9639-d525cd984032.png)

I've even tried using past versions and the error is the same. I've even tried accessing the OAuth web address and it runs Ok, but since it wasn't launched by the app, it doesn't give me a token or let's me connect inside it.

**Comment by Azd325** [comment]
Hmm, not so much on the internet on it.

Is gitkraken already in your apps in GitHub?
https://askubuntu.com/a/1099323/41186

**Comment by GuilhermeHaetinger** [comment]
> Hmm, not so much on the internet on it.
Yeah :(

> Is gitkraken already in your apps in GitHub?
Yes. I tried revoking all apps. Didn't work. Tried installing chrome as well (one of the answers on your link) and it didn't really work as well.

**Comment by Azd325** [comment]
Which desktop environment do you use?

Maybe try to install in a VirtualBox to see if maybe you have a problem in your system setup.

**Comment by GuilhermeHaetinger** [comment]
I've been using Plasma with my computer running only on Arch. I think it'll work if I use a VM (will try that later). I just wanted to know how to debug this. As I said, I ran strace on it but don't really know what the expected outcome would be. It's also not something with my connection because I tried it in a different computer and it worked. But that's as much info as I think I can get from it. Do you know a way I could maybe see if the application is running the HTTP request to the OAuth server?

**Comment by GuilhermeHaetinger** [comment]
I'm closing this because it seems to be an issue with my configuration and not the package. Thanks for the help!
