### ISSUE TITLE
GitKraken crash when clicking Preferences

### ISSUE THREAD

**Issue by UQuark0** [Azd325/gitkraken#164]
Hello. I'm using Manjaro Linux + KDE Plasma.
Currently I have GitKraken v7.5.5 installed.
When I try to open Preferences, GitKraken hangs for a few seconds and then restarts.
I'd love to attach some kind of log, but I didn't found any, and -d option does nothing for me.
Any help would be appreciated.

**Comment by Azd325** [comment]
https://github.com/Azd325/gitkraken/issues/150

**Comment by Azd325** [comment]
Try something from this ticket above there sometimes issues.

**Comment by jleask** [comment]
GitKraken v7.5.5 is crashing for me when I simply open Help>View Release Notes. It also crashes when I try to open an existing repository that was cloned from the command line, or clone a second repo from within GitKraken.

**Comment by Azd325** [comment]
Do you use KDE? Did you try this from #150 

> > I just installed GitKraken via KDE Discover an and it is now working.
> Still no idea what the problem with the AUR package is.
> I also noticed that on my notebook it is working while not on my desktop workstation.

**Comment by jleask** [comment]
No, we are using Xfce. 

I think our problem is not having the right GUI libraries available. We are going to reconfigure our containers to have hopefully the right environment needed by GitKraken.

**Comment by Azd325** [comment]
Can you check if the new version fixes the problem?

**Comment by frosty-sh** [comment]
The new version (7.6.1) didn't fix the problem for me

> gitkraken -v
> 7.6.1

I get the
> (node:40603) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:40603) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(electron) 'allowRendererProcessReuse' is deprecated and will be removed.
state:  unavailable
state:  checking
state:  unavailable
__App Window: WebContents 2 render process unexpectedly missing: crashed__
__MessagePort is terminating__

I'm using AwesomeVM on arch.

**Comment by JWestSTG** [comment]
Using 7.6.0 on XFCE4/Manjaro, same issue

**Comment by grummbeer** [comment]
@TerrorSquad, Jetbrains user? https://github.com/Azd325/gitkraken/issues/150#issuecomment-995566080

**Comment by TerrorSquad** [comment]
@grummbeer  yes. I several of their products installed. Toolbox, Phpstorm, Webstorm, GoLand and DataGrip.

**Comment by grummbeer** [comment]
Then there is a high probability that the font "JetBrains Mono" is also responsible. Could you send Axosoft a hint? More feedback > higher priority?

On the other hand ... other fonts are also affected, who needs to focus on this? The font creator, axosoft, gnome? No Idea.

**Comment by Luc45** [comment]
If you're on Arch: `sudo pacman -R ttf-inconsolata`

**Comment by sTiKyt** [comment]
> If you're on Arch: `sudo pacman -R ttf-inconsolata`

That was it, worked
