### ISSUE TITLE
Not exactly an issue bit maybe interesting nonetheless. pacman/yay seem to confuse the single installed version.

### ISSUE THREAD

**Issue by cocoonkid** [Azd325/gitkraken#172]
When installing from AUR it shows all other gitkraken as installed as well which seems to block the ability to spot the most recent version and update it automatically when doing a system update.

3 aur/gitkraken 7.6.1-1 (+257 2.72) (Installed: 7.5.5-1)
    The intuitive, fast, and beautiful cross-platform Git client.
2 chaotic-aur/gitkraken 7.5.5-1 (96.3 MiB 285.9 MiB) (Installed)
    The intuitive, fast, and beautiful cross-platform Git client.
1 arcolinux_repo_xlarge/gitkraken 7.5.5-1 (96.3 MiB 285.9 MiB) (Installed)
    The intuitive, fast, and beautiful cross-platform Git client.
==> Packages to install (eg: 1 2 3, 1-3 or ^4)

I had to manually update it via ```yay upgrade gitkraken``` which worked.

**Comment by thenexxuz** [comment]
it seems like that would be a problem with yay/yoart/pacman/etc. not telling the difference between packages from different repositories with the same name. I have never had this issue on any Arch/Manjaro/EndeavorOS install and I've been using one of these distros for the past 6-7 years, but I only use the distro repos + standard AUR.
