### ISSUE TITLE
Shows an empty window after an empty splash

### ISSUE THREAD

**Issue by ChrisLauinger77** [Azd325/gitkraken#193]
OS debian bookworm
installed using deb
latest version (8.4) from today.

This is the output when I start with a console:
`/usr/share/gitkraken/gitkraken

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:65836) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `gitkraken --trace-deprecation ...` to show where the warning was created)
(node:65836) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
state:  unavailable
state:  checking
state:  unavailable
(node:65836) UnhandledPromiseRejectionWarning: Error: too many requests
    at buildError (/usr/share/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:1106154)
    at IncomingMessage.<anonymous> (/usr/share/gitkraken/resources/app.asar/src/main/static/main.bundle.js:2:1107312)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:65836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:65836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Azd325** [comment]
Please share this with axisoft. This repo bundles gitkraken for archlinux.
