### ISSUE TITLE
stuck in login

### ISSUE THREAD

**Issue by isaac-xu-newbee** [Azd325/gitkraken#198]
I cant login

![17 06 2022_16 33 47_REC](https://user-images.githubusercontent.com/106723398/174229016-16aa0628-9b1c-4dea-b876-8371464fa680.png)

**Comment by thenexxuz** [comment]
This seems like something to address with GitKraken, the company. This project is just packaging the application for use on Arch based distros and is not affiliated/supported directly by the company. Try https://gitkraken.slack.com

**Comment by thenexxuz** [comment]
This seems like something to address with GitKraken, the company. This project is just packaging the application for use on Arch based distros and is not affiliated/supported directly by the company. Try https://gitkraken.slack.com
