### ISSUE TITLE
multilingual

### ISSUE THREAD

**Issue by zane0904** [Azd325/gitkraken#201]
Hello, is gitkraken planning to support Chinese or multilingual？thank you

**Comment by Azd325** [comment]
This seems like something to address with GitKraken, the company. This project is just packaging the application for use on Arch based distros and is not affiliated/supported directly by the company. Try https://gitkraken.slack.com/

**Comment by zane0904** [comment]
> 这似乎是与公司Gitkraken解决的问题。该项目只是将应用程序包装在基于ARCH的发行版中，并且不直接由公司隶属/支持。尝试https://gitkraken.slack.com/

OK, thank you for your reply
