### ISSUE TITLE
8.10 will no longer open

### ISSUE THREAD

**Issue by TheSHEEEP** [Azd325/gitkraken#205]
I have just upgraded to GitKraken 8.10, but the program will no longer open.

On the console all I can see is this:
```
gitkraken 
[3975:1011/155752.511137:FATAL:fork_and_spawn.cc(196)] posix_spawn: Permission denied (13)
[3889:1011/155752.511363:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

I'm running Manjaro and an AMD GPU, if that helps anyhow (since there is a GPU-related issue mentioned in the output).

The previous version worked perfectly fine (and still does, I went back to 8.9.1 as I need this tool to work).

**Comment by r2binx** [comment]
Same here on Arch w/ Gnome & Intel iGPU, regardless whether X11 or Wayland.
Flatpak users are reporting the same issue (including myself w/ Fedora 36): https://github.com/flathub/com.axosoft.GitKraken/issues/158

**Comment by r2binx** [comment]
My guess is a permission issue. After setting `chmod 755 /opt/gitkraken/chrome_crashpad_handler` it's running _fine_

**Comment by Azd325** [comment]
Merged in https://github.com/Azd325/gitkraken/commit/defcd7ff1044e684c4c82c4a6f36f38c1e0cdcc7
