### ISSUE TITLE
Investigate explicit permissions for files

### ISSUE THREAD

**Issue by Azd325** [Azd325/gitkraken#207]
https://github.com/Azd325/gitkraken/pull/206#issuecomment-1275715179

> While this may fix the issue for 8.10, I have a deeper question. Why the setup process overrides all files permissions to 644 then update some to 755 ?
> 
> The current pkg from gitkraken server has more files set to 755 (`*.so` libraries, etc.), no special permissions on `/opt/gitkraken/resources/app.asar.unpacked/resources/cli/unix/gkrc`, no setuid change on `chrome-sandbox` (755 instead of 4755), etc. So why should we perform the following chmod ?
> 
> On my side, I get a perfectly fine 8.10 package installed and ready to run with that change on PKGBUILD:
> 
> ```diff
> diff --git i/gitkraken-aur/PKGBUILD w/gitkraken-aur/PKGBUILD
> index d1d073d..fa8c054 100644
> --- i/gitkraken-aur/PKGBUILD
> +++ w/gitkraken-aur/PKGBUILD
> @@ -37,13 +37,6 @@ package() {
>      install -d "$pkgdir"/opt
>      cp -R "$srcdir"/gitkraken "$pkgdir"/opt/gitkraken
>  
> -    find "$pkgdir"/opt/gitkraken/ -type f -exec chmod 644 {} \;
> -    chmod 755 "$pkgdir"/opt/gitkraken/gitkraken
> -    chmod 755 "$pkgdir"/opt/gitkraken/resources/app.asar.unpacked/src/js/redux/domain/AskPass/AskPass.sh
> -    chmod 755 "$pkgdir"/opt/gitkraken/resources/app.asar.unpacked/resources/cli/unix/gk
> -    chmod 755 "$pkgdir"/opt/gitkraken/resources/app.asar.unpacked/resources/cli/unix/gkrc
> -    chmod 4755 "$pkgdir"/opt/gitkraken/chrome-sandbox
> -
>      install -d "$pkgdir"/usr/bin
>  
>      install -D -m755 "./gitkraken.sh" "${pkgdir}/usr/bin/gitkraken"
> ```
> 
> @Azd325 can you clarify the reason to perform manual updates on files permissions in PKGBUILD ?

**Comment by alorence** [comment]
Indeed, the very first commit of this repository started with this method: https://github.com/Azd325/gitkraken/commit/3ccf7959ec0b

Maybe the very first versions of GitKraken package were shipped with invalid permissions, or the `makepkg` command were not respecting original files permissions when extracting. I really don't know.

Anyway, I think removing entirely this process can reduce the risk to have new bugs like #205. But I am not sure of the implications. Is there a security risk to let GitKraken put executable files in the package they release ?
