### ISSUE TITLE
Unable to update to 2.4

### ISSUE THREAD

**Issue by polarathene** [Azd325/gitkraken#36]
I'm a user from Manjaro, when updating I'm given the error:

```
could not satisfy dependencies
libcurl-openssl-1.0: requires openssl-1.0
gitkraken: requires libcurl-openssl-1.0
```

I have libcurl-compat 7.52.1-1 from community repo. I noticed in https://github.com/Azd325/gitkraken/commit/8765bc5c6162b202a6099a9b0c23f7cc240e1cda this package was switched to use a specific version of libcurl instead. I'm not too familiar with dependencies for packages, but presumably that would have just been downloaded with the update if supported? I see the package is available in the AUR only.

Is this an issue due to using Manjaro or an issue with the PKGBUILD? Do I just download the AUR package and update GitKraken should work?(assuming this won't remove libcurl-compat and break other packages depending on it).

**Comment by Azd325** [comment]
I think in some days it should also availble in manjaro. 
Otherwise you have to edit the PKGBUILD or revert a commit because it will not more work with libcurl-compat 7.53 comes out.

**Comment by polarathene** [comment]
I can wait if that's the case :) Is this just a temporary dependency change that will be reverted once the prior package is updated and building Gitkraken with it again?

**Comment by Azd325** [comment]
It will and it seems that 7.54 will wotk again but we will see

**Comment by marcelloinfoweb** [comment]
I had to remove the program thinking that it could solve, but now I can not but install. What do I have to do to install by AUR in Manjaro?

**Comment by polarathene** [comment]
@marcelloinfoweb if you still have the old package in the cache you can install that I think, or you can try download an older package, downgrade should do it? I haven't done either before but I'm sure the Arch Wiki will have information :) There is also the openSSL 1.0 package available in AUR that might satisfy the dependency?(You can possibly try edit the pkgbuild too)

Otherwise we have to wait for the package update to move to Arch stable and AUR packages to update to it.

**Comment by MarcinWieczorek** [comment]
@marcelloinfoweb I recommend using ArchLinux instead of Manjaro, mostly because of issues with repositories. I can help you if you wish. You can also install an older package from Arch rollback repos, but keep in mind that some of your packages might have been built for a different version.

**Comment by polarathene** [comment]
@MarcinWieczorek I think some users prefer Manjaro over Arch. Even with Antergos which I had used prior(though with Gnome instead of KDE), I had a lot of problems with the system. Updates would break a bit too. Manjaro has a sweet kernel and hardware manager as well as BFQ as the default IO scheduler built into their kernel(with a few other subtle tweaks), they've adjusted some defaults compared to what you'd get with Arch too to improve the experience for desktop users.

Only real issues I've had are several times AUR packages being broken due to Manjaro having too old(xorg-server at the time held back due to AMD driver support, even if you use intel/nvidia) and too new(this openSSL one). Eventually support syncs and this doesn't happen too often. Updates are about every 2 weeks usually and tend to be well tested, so you get a semi-rolling experience with hopefully less breakage :P The more you use the AUR I guess the higher the chance you run into problems like this.

The other issue is BFQ with XFS after the 4.8 kernel seems to hard lockup at midnight(systemd timer unit) or on the 2nd resume from suspend, possibly related to my hardware as not many others have brought it up. Sadly that means I either use 4.8 only or give up on BFQ. Hopefully with 4.12 the blk-mq version will not have this problem. In the meantime I'm using a different IO scheduler.

**Comment by Azd325** [comment]
@polarathene For now you can only remove/change the dependencies in the `PKGBUILD` on your own.

**Comment by polarathene** [comment]
@Azd325 That's what I was referring @marcelloinfoweb to do, as the response was directed at him.

**Comment by MarcinWieczorek** [comment]
I use Arch because all derivatives and most of other distros are overconfigured. I need an OS suited to my needs. My setup uses <100MB ram after startup, of course everything changes as soon as I run the browser. Manjaro is easy, but it's possible to achieve something better with nothing but a little effort (and quite some knowledge and an ability to read!). That's why I offer my help :)

**Comment by Azd325** [comment]
Lock this thread for non relevant discussions to the topic. :)

**Comment by MarcinWieczorek** [comment]
Well freedom of speech exists for a reason. I agree though that this topic is difficult because everyone has their reasons to use their favorite distros. This is not the place :)

**Comment by Azd325** [comment]
I added a ticket for them. https://github.com/Azd325/gitkraken/issues/38
But Manjaro vs Arch is an endless discussion. :)
