### ISSUE TITLE
Flatpak - the future of application distribution

### ISSUE THREAD

**Issue by KillWolfVlad** [Azd325/gitkraken#42]
We should create `flatpak` package for other distributions (e.g. Fedora)

**Comment by juanpedrob9** [comment]
hrm fyi from gitkraken web site for Fedora (yeah i moved to Fedora for some reasons)... For sure you have to create desktop file but after that you only need to run that bash file..

```
#!/bin/bash

wget https://release.gitkraken.com/linux/gitkraken-amd64.tar.gz
tar -xvzf gitkraken-amd64.tar.gz
sudo rsync -va --delete-after gitkraken/ /opt/gitkraken/
rm -rf gitkraken/ gitkraken-amd64.tar.gz
```

**Comment by Ramblurr** [comment]
I would love a flatpak of gitkraken? Why was this issue closed :(
 
Yes, gitkraken has a binary release on their site, but a flatpak would be more convenient and more secure.
