### ISSUE TITLE
Isn't available in AUR

### ISSUE THREAD

**Issue by SalahAdDin** [Azd325/gitkraken#49]
See: https://aur.archlinux.org/gitkraken.git

**Comment by KillWolfVlad** [comment]
@SalahAdDin 

- Note: Git clone URLs are not meant to be opened in a browser. 
- To clone the Git repository of gitkraken, run `git clone https://aur.archlinux.org/gitkraken.git`. 
- Click [here](https://aur.archlinux.org/pkgbase/gitkraken/) to return to the gitkraken details page.

**Comment by SalahAdDin** [comment]
@KillWolfVlad I mean, if you try to install it since AUR is not possible, is no accesible.

**Comment by SalahAdDin** [comment]
Ok, i got it.

**Comment by KillWolfVlad** [comment]
@SalahAdDin 

Does gitkraken work?
