### ISSUE TITLE
Taskbar doesn't show Gitkraken logo

### ISSUE THREAD

**Issue by luzpaz** [Azd325/gitkraken#51]
![image](https://user-images.githubusercontent.com/4140247/30142769-8df69fc8-9350-11e7-8f49-394ad2aaf34b.png)

Running on Manjaro Linux 17.03 
Gitkraken 3.0

**Comment by Azd325** [comment]
Not really sure if we can fix this. I have this issue too with xfce.
I tried some different approaches didn't get it to work on my xfce but the icon is in the application launcher works fine.

**Comment by KillWolfVlad** [comment]
@MarcinWieczorek - issue is actual for XFCE

**Comment by luzpaz** [comment]
@Lctrs is there an ETA ?

**Comment by Lctrs** [comment]
Not that I'm aware of.

**Comment by thenexxuz** [comment]
Is this issue still valid? I know that GitKraken has (as of v6) updated the underlying electron base. Not sure if that will effect this at all.

**Comment by Azd325** [comment]
I have no xfce running anymore so I can't test it

**Comment by thenexxuz** [comment]
I am installing XFCE to test

**Comment by thenexxuz** [comment]
![image](https://user-images.githubusercontent.com/1750061/62736383-d9465480-b9f2-11e9-8d5b-482710ca90dc.png)
looks to be fixed now.

**Comment by luzpaz** [comment]
Yea, it's fixed.   
xfce4-panel 4.13.7git-8fb43d (Xfce 4.14pre2)
