### ISSUE TITLE
Dropdown menu missing

### ISSUE THREAD

**Issue by luzpaz** [Azd325/gitkraken#64]
After a certain update... I think it was 2 or 3 ago.. I lost the dropdown menu bar. If I push alt or ctrl key to bring it up it still doesn't work. 
![image](https://user-images.githubusercontent.com/4140247/33488864-1c307134-d680-11e7-9960-f5d73c83e1bd.png)
Manjaro Linux 17.1pre3 XFCE 4.12

**Comment by KillWolfVlad** [comment]
`manjaro-xfce-17.1-pre3-stable-x86_64.iso` fresh installation on `VirtualBox`

I can't reproduce your issue

![screenshot_2017-12-01_21-10-10](https://user-images.githubusercontent.com/18448635/33491799-28ecbb1e-d6dd-11e7-9f74-251c4b0fe4d2.png)

P.S. `GitKraken` from `AUR`

**Comment by KillWolfVlad** [comment]
Try drop your `GitKraken` profile

- ` ~/.gitkraken`
- `~/.config/GitKraken`

**Comment by luzpaz** [comment]
> Try drop your GitKraken profile
    ~/.gitkraken
    ~/.config/GitKraken

What will i lose if I delete these? BTW, thanks for checking on virtualbox!

**Comment by KillWolfVlad** [comment]
> What will i lose if I delete these? BTW, thanks for checking on virtualbox!

All `GitKraken` preferences and cache

*You also can backup these folders

**Comment by luzpaz** [comment]
I backed them up, restarted and that fixed it. Thanks!
