### ISSUE TITLE
libpsl update breaks Gitkraken

### ISSUE THREAD

**Issue by Schokobecher** [Azd325/gitkraken#75]
It seems libpsl has been updated to 6.2.0 in the meantime

which results in:

> error while loading shared libraries: libpsl.so.5: cannot open shared object file: No such file or directory

```
lrwxrwxrwx 1 root root    15 25. Feb 23:54 libpsl.so -> libpsl.so.6.2.0
lrwxrwxrwx 1 root root     9 16. Mär 18:30 libpsl.so.5 -> libpsl.so
lrwxrwxrwx 1 root root    15 25. Feb 23:54 libpsl.so.6 -> libpsl.so.6.2.0
-rwxr-xr-x 1 root root 64352 25. Feb 23:54 libpsl.so.6.2.0
```

I linked _libpsl.so_ to _libpsl.5.so_ as a workaround for now.

**Comment by Azd325** [comment]
Can you try this https://github.com/Azd325/gitkraken/pull/73?

**Comment by Schokobecher** [comment]
Ah yes, it works.
looks like I also reinstalled the package from another repo by accident.
Should have checked first :(

Thank you!
