### ISSUE TITLE
Font Issue - Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by dphilpot** [Azd325/gitkraken#77]
Hi,
im currently in a trial of Ubuntu 18.04 LTS where im having the following issue with GitKranken
![gitkraken](https://user-images.githubusercontent.com/6019830/38987384-d20d4e70-43cf-11e8-9c55-8e15ca1d6937.png)

System Specs:

OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.15.0-15-generic
DE: XFCE
WM: Xfwm4
WM Theme: Greybird
GTK Theme: Greybird [GTK2]
Icon Theme: Adwaita
Font: Noto Sans 11
GPU: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)

**Comment by KillWolfVlad** [comment]
It is repo for Arch Linux users. But I think the problem in old electron version.

**Comment by KillWolfVlad** [comment]
Looks like previous issue #45 about ugly fonts. But Ubuntu 18.04 is currently beta, and maybe bug in Ubuntu, not GitKraken.

**Comment by MarcinWieczorek** [comment]
As @KillWolfVlad said, this repository provides a package for Arch User Repository. Because this issue has nothing to do with AUR at all I have to close it. Please contact Gitkraken support as we are not related to them in any way. Thank you.

**Comment by dphilpot** [comment]
Hi,
im sorry for the missunderstanding.
