### ISSUE TITLE
There´s no Text on Init -> Gitlab.com -> Account (only main acocunt)

### ISSUE THREAD

**Issue by xmediasoftware** [Azd325/gitkraken#86]
![initialize repo error](https://user-images.githubusercontent.com/5357034/43307278-9ad21aac-9132-11e8-830b-64f0f095a7e1.png)

**Comment by MarcinWieczorek** [comment]
Probably not our fault, but why did you close it? Do you know a solution?

**Comment by xmediasoftware** [comment]
because I think that you were the creators of gitkraken, but I found my mistake

**Comment by MarcinWieczorek** [comment]
I'm glad you found out. Feel free to share a solution if you know one.

We should make it all clear in the readme, it's not the first time someone reported an issue not related to the package.
