### ISSUE TITLE
Can't open "Branch actions" context menu

### ISSUE THREAD

**Issue by KillWolfVlad** [Azd325/gitkraken#89]
### Summary

Can't open "Branch actions" context menu in GitKraken v4.0.0 and 4.0.1 under Arch Linux and Windows when branch has GitLab remote.

### Steps to Reproduce

1. Create project on GitLab (not self-hosted)
1. Clone it and open in GitKraken
1. Click to "Branch actions" on left panel or open context menu on latest commit on selected branch

![image](https://user-images.githubusercontent.com/18448635/44083945-cfa54ccc-9fce-11e8-8cff-0edb93c9595a.png)

### Expected behavior

Context menu should open

### Actual behavior

Context menu does not open

### Stack trace

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at _lodash2.default.find (/gitkraken/resources/app/src/js/helpers/PullRequestHelpers.js:274:180)
    at baseFindIndex (/gitkraken/resources/app/node_modules/lodash/lodash.js:740:11)
    at findIndex (/gitkraken/resources/app/node_modules/lodash/lodash.js:6741:14)
    at Function.find (/gitkraken/resources/app/node_modules/lodash/lodash.js:4727:21)
    at Object.getRemoteFromPullRequest (/gitkraken/resources/app/src/js/helpers/PullRequestHelpers.js:265:45)
    at Object.getBaseRemoteFromPullRequest (/gitkraken/resources/app/src/js/helpers/PullRequestHelpers.js:202:42)
    at Object.getRemoteFromParentInfo (/gitkraken/resources/app/src/js/helpers/HostingServiceHelpers.js:292:42)
    at addAppropriateStartPullRequestOptions (/gitkraken/resources/app/src/js/helpers/ContextMenuHelpers.js:879:57)
    at _promise2.default.resolve.then.then (/gitkraken/resources/app/src/js/helpers/ContextMenuHelpers.js:924:35)
    at tryCallOne (/gitkraken/resources/app/node_modules/promise/lib/core.js:37:12)
    at /gitkraken/resources/app/node_modules/promise/lib/core.js:123:15
    at flush (/gitkraken/resources/app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

### Reverse Engineering

What happens in method `getRemoteFromPullRequest` (in file `/gitkraken/resources/app/src/js/helpers/PullRequestHelpers.js`)?

|  Local variable    | Value                                                                                                 |
|--------------------|-------------------------------------------------------------------------------------------------------|
| hostingServiceType | gitlab                                                                                                |
| remoteType         | base                                                                                                  |
| pullRequest        | {"hostingServiceType":"gitlab","base":{"repo":{"name":"SecretRepo"},"owner":{"login":"SecretLogin"}}} |

Next, looks to the code on line 274

```javascript
const repoName = hostingServiceType === _constants2.default.HostingService.types.GITLAB ? _fp2.default.getOr('', [remoteType, 'repo', 'fullName'], pullRequest).split('/')[1].toLowerCase() : _fp2.default.getOr('', [remoteType, 'repo', 'name'], pullRequest).toLowerCase();
```

`pullRequest` doesn't have property `base.repo.fullName`, so `lodash/fp.getOr` always return empty string. If you split empty string by slash, you will get array with one item - empty string. Array with one item doesn't have item on index 1 and return `undefined`.

**Comment by KillWolfVlad** [comment]
I think it would be helpful to notify @Axosoft about this issue.

**Comment by KillWolfVlad** [comment]
Unfortunately Asosoft doesn't provide guaranteed support for free accounts. Anyway you can apply this **legal** patch.

```diff
--- a/app/src/js/helpers/PullRequestHelpers.js
+++ b/app/src/js/helpers/PullRequestHelpers.js
@@ -271,7 +271,8 @@ const PullRequestHelpers = {
 
       // For GitLab `name` is a human readable string (e.g. 'GitLab Community Edition') and we need to extract
       // the repo name used for building URLs (e.g. 'gitlab-ce')
-      const repoName = hostingServiceType === _constants2.default.HostingService.types.GITLAB ? _fp2.default.getOr('', [remoteType, 'repo', 'fullName'], pullRequest).split('/')[1].toLowerCase() : _fp2.default.getOr('', [remoteType, 'repo', 'name'], pullRequest).toLowerCase();
+      const fullName = _fp2.default.getOr('', [remoteType, 'repo', 'fullName'], pullRequest);
+      const repoName = hostingServiceType === _constants2.default.HostingService.types.GITLAB && fullName ? fullName.split('/')[1].toLowerCase() : _fp2.default.getOr('', [remoteType, 'repo', 'name'], pullRequest).toLowerCase();
 
       return pullRequest.hostingServiceType === hostingServiceType && parsedRemoteUrl.owner.toLowerCase() === ownerName && parsedRemoteUrl.name.toLowerCase() === repoName;
     });
```

You can find PKGBUILD with this patch [here](https://github.com/KillWolfVlad/gitkraken/tree/fix/branch-actions)

**Comment by MarcinWieczorek** [comment]
Have you reported that to Axosoft already? I guess they don't support free users having trouble with their poor knowledge of computers, but a patch won't hurt them in any way.

**Comment by KillWolfVlad** [comment]
> Have you reported that to Axosoft already?

Yes. Via "Feedback" in GitKraken.

**Comment by MarcinWieczorek** [comment]
I remember myself reporting something a long time ago, I couldn't find any real contact method.

**Comment by KillWolfVlad** [comment]
Issue is still actual for GitKraken v4.0.2

**Comment by MarcinWieczorek** [comment]
I vote for applying the patch in the PKGBUILD.
@Azd325 ?

**Comment by KillWolfVlad** [comment]
Why not? We can merge my [branch](https://github.com/KillWolfVlad/gitkraken/tree/fix/branch-actions)

**Comment by MarcinWieczorek** [comment]
This time don't ask me why not. I'm not the owner here. I don't want to be against every your patch because of the past. This one actually helps the project.

**Comment by MarcinWieczorek** [comment]
I know you don't mind, that was a word game from the previous PR titled something like "why don't we" lol. Let's wait and do a little voting here.

**Comment by Azd325** [comment]
I got a message form the gitkraken team that they have this on there TODO List, so I don't see a reason  to patch this.

**Comment by MarcinWieczorek** [comment]
I see nothing against patching it till they get it that fixed.
